# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed20931bf3c7f030271c76476faeef69a0ce60612c0c73fc37287e7feec568677089cae826d12e843f03352d9b16304d8474c8d7e689c58709eeef435c41aa48

test:
  secret_key_base: 1a936c80104d7f03e42bb55c958e06e43623914e48bba9cd1d633238228a5129275b4dee4b74aa4b15e404c9e470c3821cc3fe0d865dc68be69044b3422055a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
